### ISSUE TITLE
Missing property "input" for schedule event

### ISSUE THREAD

**Issue by carlin-q-scott** [threadheap/serverless-ide-vscode#52] opened 2019-11-05 19:45 UTC
I'm getting the following lint error for my schedule event:
> Missing property "input"

This property is not required, at least [not for AWS](https://serverless.com/framework/docs/providers/aws/events/schedule/).

**Comment by pavelvlasov** [comment] 2019-11-06 20:32
Thanks for reporting @carlin-q-scott 👍 The issue is fixed in the latest version of the plugin.

**Closed by pavelvlasov** 2019-11-06 20:32 UTC

**Comment by carlin-q-scott** [comment] 2019-11-07 15:52
Wow, that's the fastest response I've ever gotten from a FOSS project. Thanks!
