### ISSUE TITLE
Wrong error highlight when using artifact with serverless framewok layers

### ISSUE THREAD

**Issue by AllanPamplona** [threadheap/serverless-ide-vscode#81] opened 2020-04-25 21:05 UTC
I am using Serverless IDE 0.5.18. I am creating a Lambda layer using Serverless framework.
Having followed the documentation: 
```You can also specify a prebuilt archive to create your layer. When you do this, you do not need to specify the path element of your layer.```

I got a: 
[Serverless IDE] Missing property "path".
Also a:
[Serverless IDE] Unexpected property package

is being displayed.
The expected behavior is don't require a path if there is a package attribute inside the layer.
![2020-04-25-160325_376x135_scrot](https://user-images.githubusercontent.com/13873487/80290921-9fe37f80-870e-11ea-9402-7281fa324e82.png)

**Comment by pavelvlasov** [comment] 2020-05-02 07:14
Thanks for reporting @AllanPamplona 👍 The issue is fixed in the latest release.

**Closed by pavelvlasov** 2020-05-02 07:14 UTC
