### ISSUE TITLE
UpdateReplacePolicy errors

### ISSUE THREAD

**Issue by fragallia** [threadheap/serverless-ide-vscode#49] opened 2019-10-21 06:34 UTC
When I put `UpdateReplacePolicy: Retain` directive into e.g. `AWS::Cognito::UserPool` resource definition, it shows error.

```
    UserPool:
      Type: "AWS::Cognito::UserPool"
      UpdateReplacePolicy: Retain
      Properties:
        ...
```

**Comment by pavelvlasov** [comment] 2019-10-26 07:19
thanks for reporting @fragallia 👍 the issue is resolved in v0.5.0

**Closed by pavelvlasov** 2019-10-26 07:19 UTC
