### ISSUE TITLE
serverless-ide crashing because of ill-formed json config

### ISSUE THREAD

**Issue by sfried** [threadheap/serverless-ide-vscode#64] opened 2020-01-17 04:54 UTC
Not sure what happened (I clicked something and ending up searching in the cfn-lint output pane). I clicked into the regular editor pane, and then the serverless-ide was terminated by vscode because of the following crash.  Obviously, I created a json file somewhere (still not sure where) that the extension did not expect, and was not coded to handle.  I've checked all of the .json files in ~/.config/Code and ~/.vscode, and all of them that are recently modified are valid json.

undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ChildProcess.<anonymous> (/home/steve/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/@serverless-ide/language-server/dist/language-service/services/validation/index.js:110:41)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
[Info  - 11:37:46 PM] Connection to server got closed. Server will restart.
[Error - 11:37:47 PM] (node:27853) UnhandledPromiseRejectionWarning: Error: Unhandled method workplace/list
    at handleResponse (/home/steve/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:436:48)
    at processMessageQueue (/home/steve/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:263:17)
    at Immediate.<anonymous> (/home/steve/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at processImmediate (internal/timers.js:439:21)
[Error - 11:37:47 PM] (node:27853) UnhandledPromiseRejectionWarning: Error: Unhandled method workplace/list
    at handleResponse (/home/steve/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:436:48)
    at processMessageQueue (/home/steve/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:263:17)
    at Immediate.<anonymous> (/home/steve/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at processImmediate (internal/timers.js:439:21)
[Error - 11:37:47 PM] (node:27853) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[Error - 11:37:47 PM] (node:27853) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[Error - 11:37:47 PM] (node:27853) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 11:37:47 PM] (node:27853) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by sfried** [comment] 2020-01-17 05:01
Turns out that the following line in my cloud formation script broke things:

  Value:  !!Ref AValidRef

deleting one of the bangs fixed the problem.

**Comment by pavelvlasov** [comment] 2020-01-17 22:01
thanks for investigation @sfried!
It makes sense to make it less error-prone in case of failed yaml -> json transformation.

**Comment by returnzer0** [comment] 2020-01-22 16:39
I am experiencing the same error but I am not using and Ref functions, just !Sub, !GetAtt. The stack uploads without issues so I am not sure why I am getting this error.

**Comment by pavelvlasov** [comment] 2020-01-22 20:43
@returnzer0 can you share what kind of attributes you have in `!Sub` and `!GetAtt` by any chance?

**Comment by returnzer0** [comment] 2020-01-22 21:16
Hi,
I just realized it happens with every template for some reason. If I open a simple template in the visual studio code editor, the error happens. It tries to restart the plugin three times but every single time I get the same output. Here is the full output

undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ChildProcess.<anonymous> (/Users/munib/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/@serverless-ide/language-server/dist/language-service/services/validation/index.js:110:41)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
[Info  - 2:14:41 PM] Connection to server got closed. Server will restart.
[Error - 2:14:41 PM] (node:60842) UnhandledPromiseRejectionWarning: Error: Unhandled method workplace/list
    at handleResponse (/Users/munib/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:436:48)
    at processMessageQueue (/Users/munib/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:263:17)
    at Immediate.<anonymous> (/Users/munib/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at processImmediate (internal/timers.js:439:21)
[Error - 2:14:41 PM] (node:60842) UnhandledPromiseRejectionWarning: Error: Unhandled method workplace/list
    at handleResponse (/Users/munib/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:436:48)
    at processMessageQueue (/Users/munib/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:263:17)
    at Immediate.<anonymous> (/Users/munib/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at processImmediate (internal/timers.js:439:21)
[Error - 2:14:41 PM] (node:60842) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[Error - 2:14:41 PM] (node:60842) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[Error - 2:14:41 PM] (node:60842) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 2:14:41 PM] (node:60842) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ChildProcess.<anonymous> (/Users/munib/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/@serverless-ide/language-server/dist/language-service/services/validation/index.js:110:41)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
[Info  - 2:14:42 PM] Connection to server got closed. Server will restart.
[Error - 2:14:43 PM] (node:60848) UnhandledPromiseRejectionWarning: Error: Unhandled method workplace/list
    at handleResponse (/Users/munib/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:436:48)
    at processMessageQueue (/Users/munib/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:263:17)
    at Immediate.<anonymous> (/Users/munib/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at processImmediate (internal/timers.js:439:21)
[Error - 2:14:43 PM] (node:60848) UnhandledPromiseRejectionWarning: Error: Unhandled method workplace/list
    at handleResponse (/Users/munib/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:436:48)
    at processMessageQueue (/Users/munib/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:263:17)
    at Immediate.<anonymous> (/Users/munib/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at processImmediate (internal/timers.js:439:21)
[Error - 2:14:43 PM] (node:60848) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[Error - 2:14:43 PM] (node:60848) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[Error - 2:14:43 PM] (node:60848) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 2:14:43 PM] (node:60848) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ChildProcess.<anonymous> (/Users/munib/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/@serverless-ide/language-server/dist/language-service/services/validation/index.js:110:41)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
[Info  - 2:14:44 PM] Connection to server got closed. Server will restart.
[Error - 2:14:45 PM] (node:60852) UnhandledPromiseRejectionWarning: Error: Unhandled method workplace/list
    at handleResponse (/Users/munib/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:436:48)
    at processMessageQueue (/Users/munib/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:263:17)
    at Immediate.<anonymous> (/Users/munib/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at processImmediate (internal/timers.js:439:21)
[Error - 2:14:45 PM] (node:60852) UnhandledPromiseRejectionWarning: Error: Unhandled method workplace/list
    at handleResponse (/Users/munib/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:436:48)
    at processMessageQueue (/Users/munib/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:263:17)
    at Immediate.<anonymous> (/Users/munib/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at processImmediate (internal/timers.js:439:21)
[Error - 2:14:45 PM] (node:60852) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[Error - 2:14:45 PM] (node:60852) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[Error - 2:14:45 PM] (node:60852) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 2:14:45 PM] (node:60852) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ChildProcess.<anonymous> (/Users/munib/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/@serverless-ide/language-server/dist/language-service/services/validation/index.js:110:41)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
[Info  - 2:14:46 PM] Connection to server got closed. Server will restart.
[Error - 2:14:47 PM] (node:60856) UnhandledPromiseRejectionWarning: Error: Unhandled method workplace/list
    at handleResponse (/Users/munib/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:436:48)
    at processMessageQueue (/Users/munib/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:263:17)
    at Immediate.<anonymous> (/Users/munib/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at processImmediate (internal/timers.js:439:21)
[Error - 2:14:47 PM] (node:60856) UnhandledPromiseRejectionWarning: Error: Unhandled method workplace/list
    at handleResponse (/Users/munib/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:436:48)
    at processMessageQueue (/Users/munib/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:263:17)
    at Immediate.<anonymous> (/Users/munib/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at processImmediate (internal/timers.js:439:21)
[Error - 2:14:47 PM] (node:60856) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[Error - 2:14:47 PM] (node:60856) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[Error - 2:14:47 PM] (node:60856) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 2:14:47 PM] (node:60856) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ChildProcess.<anonymous> (/Users/munib/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.12/node_modules/@serverless-ide/language-server/dist/language-service/services/validation/index.js:110:41)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
[Error - 2:14:48 PM] Connection to server got closed. Server will not be restarted.

**Comment by rzyns** [comment] 2020-03-24 13:44
I just started running into this issue, and in my case, it seems to be because of this: homebrew-core/51839 (ultimately caused by aws-cloudformation/cfn-python-lint#1434).

Looking at the code in `~/.vscode/extensions/threadheap.serverless-ide-vscode-0.5.16/node_modules/@serverless-ide/language-server/dist/language-service/services/validation/index.js` (looks like `@serverless-ide/language-server` is published to NPM, but not a publicly-accessible Github repo), I see this (lines 108-111):

```javascript
    child.on("exit", () => {
      const tmp = output.toString();
      const errors = JSON.parse(tmp);
      if (Array.isArray(errors)) {
```

So, basically it looks like any time the `cfn-lint` binary emits invalid JSON data to its standard output, the language server will crash on the exception thrown by `JSON.parse()`. This includes _no_ output, as in the case of a Python error/exception in `cfn-lint` which is generated before any output is emitted (as in aws-cloudformation/cfn-python-lint#1434; all the traceback data is output to stderr). Throwing a `try`/`catch` around the `JSON.parse()` confirms this.

For reference, here's the aforementioned traceback data I see when invoking `cfn-lint`:

```
Traceback (most recent call last):
  File "/usr/local/bin/cfn-lint", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/Cellar/cfn-lint/0.29.0/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3255, in <module>
    def _initialize_master_working_set():
  File "/usr/local/Cellar/cfn-lint/0.29.0/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3238, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/Cellar/cfn-lint/0.29.0/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3267, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/Cellar/cfn-lint/0.29.0/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/local/Cellar/cfn-lint/0.29.0/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/Cellar/cfn-lint/0.29.0/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'networkx~=2.4' distribution was not found and is required by cfn-lint
```

I'm hoping that aws-cloudformation/cfn-python-lint#1434 and homebrew-core/51839 are closed quickly so I don't have to work directly with `pip` to install an older version of `cfn-lint` ;)

**Comment by chenrui333** [comment] 2020-03-25 04:10
FYI, just pushed a fix per https://github.com/Homebrew/homebrew-core/pull/52082, let me know if the issue got fixed now. Sorry about the hassle.

**Comment by chenrui333** [comment] 2020-03-25 15:08
I think it should be good to close now (the cfn-lint issue one got closed)

**Comment by pavelvlasov** [comment] 2020-03-25 22:55
Thanks for a quick fix @chenrui333 👍 It makes sense to keep this open, to make some changes in serverless-ide for better error reporting if that will happen in the future.

**Comment by pavelvlasov** [comment] 2020-03-29 01:56
The plugin should be more resilient to such cases in the latest version. Feel free to reopen if that happens again.

**Closed by pavelvlasov** 2020-03-29 01:56 UTC

**Comment by txynidakis** [comment] 2020-07-18 01:13
Hi I seem to be experiencing a similar issue 

I only experience the issue when serverless-ide is enabled/installed

Serverless IDE 0.5.24

$ cfn-lint --version
cfn-lint 0.34.0

VS Code info 


Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:18:50.054Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

The error output is
`Traceback (most recent call last):
  File "/usr/local/bin/cfn-lint", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/cfnlint/__main__.py", line 24, in main
    (args, filenames, formatter) = cfnlint.core.get_args_filenames(sys.argv[1:])
  File "/usr/local/lib/python3.8/site-packages/cfnlint/core.py", line 113, in get_args_filenames
    config = cfnlint.config.ConfigMixIn(cli_args)
  File "/usr/local/lib/python3.8/site-packages/cfnlint/config.py", line 490, in __init__
    ConfigFileArgs.__init__(
  File "/usr/local/lib/python3.8/site-packages/cfnlint/config.py", line 70, in __init__
    self.load()
  File "/usr/local/lib/python3.8/site-packages/cfnlint/config.py", line 138, in load
    user_config = self._read_config(self.__user_config_file)
  File "/usr/local/lib/python3.8/site-packages/cfnlint/config.py", line 224, in _read_config
    config_template = cfnlint.decode.cfn_yaml.load(str(config))
  File "/usr/local/lib/python3.8/site-packages/cfnlint/decode/cfn_yaml.py", line 211, in load
    return loads(content, filename)
  File "/usr/local/lib/python3.8/site-packages/cfnlint/decode/cfn_yaml.py", line 189, in loads
    template = loader.get_single_data()
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "ext/_yaml.pyx", line 707, in _yaml.CParser.get_single_node
  File "ext/_yaml.pyx", line 725, in _yaml.CParser._compose_document
  File "ext/_yaml.pyx", line 776, in _yaml.CParser._compose_node
  File "ext/_yaml.pyx", line 890, in _yaml.CParser._compose_mapping_node
  File "ext/_yaml.pyx", line 732, in _yaml.CParser._compose_node
  File "ext/_yaml.pyx", line 905, in _yaml.CParser._parse_next_event
yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 2, column 1
could not find expected ':'
  in "<unicode string>", line 3, column 1
`
Can someone please help?!
