### ISSUE TITLE
COGNITO_USER_POOLS: [Serverless IDE] Matches multiple schemas when only one must validate.

### ISSUE THREAD

**Issue by rcoundon** [threadheap/serverless-ide-vscode#114] opened 2020-12-16 18:29 UTC
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template

* **What is the current behavior?**
When using COGNITO_USER_POOLS as an authorizer type the plugin reports:

[Serverless IDE] Matches multiple schemas when only one must validate.

![image](https://user-images.githubusercontent.com/9136570/102390515-6678c080-3fcc-11eb-97e8-c90949a86aec.png)

* **What is the expected behavior?**
COGNITO_USER_POOLS is a valid value in a serverless framework template so should not flag an error

* **What is the motivation / use case for changing the behavior?**
To prevent invalid error message

* **Please tell us about your environment:**
  
  - Plugin version: 0.5.28
  - VSCode version: 1.52.0
  - Template type: serverless framework

This could be related to #113

**Comment by faheel** [comment] 2020-12-23 03:57
I think the issue is because in [this recent change](https://github.com/threadheap/serverless-ide-vscode/commit/03d898cb8718e676f9dbdc430dbd0731bfeb8ae7#diff-00dfd2efd954a8847604bf8d3702482415cc952884c373b68138956534f935fcR48-R66) the 2nd rule under `oneOf` will match all of those strings that were already matched in the first rule, hence the "Matches multiple schemas" error is returned.

This can probably be fixed by changing `oneOf` to `anyOf`.

**Comment by pavelvlasov** [comment] 2020-12-27 22:31
@faheel changing to "anyOf" fixes the problems, thanks for suggesting! The fix is out with the latest release.

**Closed by pavelvlasov** 2020-12-27 22:31 UTC
